In [1]:
import pandas as pd
import numpy as np 
import sys 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from constants import DATA_PATH

In [63]:
rank = pd.read_csv(f"{DATA_PATH}Ratings.csv")
books = pd.read_csv(f"{DATA_PATH}Books.csv")
books

/var/folders/rm/52snk1ts6lv7smxnr467kzbx2hmb6p/T/ipykernel_73218/1096944142.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(f"{DATA_PATH}Books.csv")

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

In [10]:
rank = pd.read_csv(f"{DATA_PATH}Ratings.csv")
books = pd.read_csv(f"{DATA_PATH}Books.csv")
rank.columns = [col.lower() for col in rank.columns]
books.columns = [col.lower() for col in books.columns]
books = books[["isbn", "book-title", "book-author"]]
books

/var/folders/rm/52snk1ts6lv7smxnr467kzbx2hmb6p/T/ipykernel_73218/1423601126.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(f"{DATA_PATH}Books.csv")

,isbn,book-title,book-author
0,0195153448,Classical Mythology,Mark P. O. Morford
1,0002005018,Clara Callan,Richard Bruce Wright
2,0060973129,Decision in Normandy,Carlo D'Este
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata
4,0393045218,The Mummies of Urumchi,E. J. W. Barber
...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger
271356,0525447644,From One to One Hundred,Teri Sloat
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker
271358,0192126040,Republic (World's Classics),Plato
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle

In [11]:
rank = pd.merge(rank, books, on="isbn")
rank.columns = ["user", "isbn", "rating", "title", "author"]

In [12]:
rank

,user,isbn,rating,title,author
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose
...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane

In [45]:
def calc_corr_for_df(target_index: str, rank: pd.DataFrame, groupby_col: str):
    # We can evaluate correlations only for books which were read by the same users
    target_groupby_col = f"target_{groupby_col}"

    target_users = rank.loc[rank[groupby_col] == target_index, "user"].unique()
    filtered_rank = rank[rank.user.isin(target_users)]

    target_book_rank = filtered_rank[filtered_rank[groupby_col] == target_index]

    target_book_rank = target_book_rank.rename(columns={"rating": "target_rating", groupby_col: target_groupby_col})
    other_books_rank = filtered_rank[filtered_rank[groupby_col] != target_index]
    rank_target_other_book = pd.merge(other_books_rank, target_book_rank, on=["user"])
    # Calc mean, std for books.
    books_stats = (rank_target_other_book.groupby([groupby_col, target_groupby_col])
                   .agg({"rating": ["mean", "std"], "target_rating": ["mean", "std"]}).reset_index())
    books_stats.columns = [groupby_col, target_groupby_col, "mean", "std", "target_mean", "target_std"]
    # std == 0 <=> less than one rank value. Can't recommend in that case
    books_stats = books_stats[(books_stats['std'] > 0) & (books_stats['target_std'] > 0)]
    if len(books_stats) == 0:
        return books_stats
    books_stats = pd.merge(rank_target_other_book, books_stats, on=[groupby_col, target_groupby_col])
    # Added temp col for corr computations
    books_stats["almost_corr"] = (
            ((books_stats["rating"] - books_stats["mean"]) * (books_stats["target_rating"] - books_stats["target_mean"]))
            / books_stats["std"] / books_stats["target_std"]
    )
    books_corr = books_stats.groupby([groupby_col, target_groupby_col]).agg({"almost_corr": "sum", "user": "count"})
    books_corr = books_corr.reset_index()
    books_corr["corr"] = books_corr["almost_corr"] / (books_corr["user"] - 1)
    return books_corr


stats = calc_corr_for_df("God Emperor of Dune (Dune Chronicles, Book 4)", rank[["user", "rating", "title"]], "title")
stats.sort_values("corr", ascending=False).head(40)

,title,target_title,almost_corr,user,corr
1872,The Right Hand of Evil,"God Emperor of Dune (Dune Chronicles, Book 4)",5.0,6,1.0
1215,"Ramona Quimby, Age 8 (Avon Camelot Books (Pape...","God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
1454,Tales of a Fourth Grade Nothing,"God Emperor of Dune (Dune Chronicles, Book 4)",6.0,7,1.0
508,Enticed,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
196,Bellwether,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1406,Ssn,"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
176,Bartleby and Benito Cereno (Dover Thrift Editi...,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1519,The Bourne Supremacy,"God Emperor of Dune (Dune Chronicles, Book 4)",7.0,8,1.0
450,Dracula (World's Classics),"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
1588,The Darwin Awards: Evolution in Action,"God Emperor of Dune (Dune Chronicles, Book 4)",3.0,4,1.0
1462,Tehanu: The Last Book Of Earthsea (Earthsea T...,"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
1389,Son of Rosemary: The Sequel to Rosemary's Baby,"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
513,Eternity,"God Emperor of Dune (Dune Chronicles, Book 4)",4.0,5,1.0
228,Body of Evidence,"God Emperor of Dune (Dune Chronicles, Book 4)",3.0,4,1.0
2108,Vet in harness,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1975,The Vampire Companion: The Official Guide to A...,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
223,"Blood of the Fold (Sword of Truth, Book 3)","God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
2106,Velvet Angel,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1974,The Vampire Book: The Encyclopedia of the Undead,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
232,Booked to Die (Cliff Janeway Novels (Paperback)),"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
1470,That Hideous Strength (A Modern Fairy-Tale for...,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1741,The Ladies of Mandrigyn (Unschooled Wizard 1),"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
510,Essays (Penguin Classics),"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
586,Footfall,"God Emperor of Dune (Dune Chronicles, Book 4)",3.0,4,1.0
1203,RAISE THE TITANIC (Clive Cussler),"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
247,Brighty : Of the Grand Canyon (Marguerite Henr...,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1986,The Wasp Factory,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
2093,Unpleasant Profession of Jonathan Hoag,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
252,Buffy the Vampire Slayer: Origin,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
251,Buffy the Vampire Slayer and Philosophy: Fear ...,"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
2095,Untitled: A Booklover's Mystery (Booklover's M...,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
494,Elric: Tales of the White Wolf (Michael Moorco...,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
2098,V: The Chicago Conversion,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1018,Mrs. Frisby and the Rats of Nimh,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
501,"Encyclopedia of Gods: Over 2,500 Deities of th...","God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1752,The Lays of Beleriand (The History of Middle-E...,"God Emperor of Dune (Dune Chronicles, Book 4)",2.0,3,1.0
497,Emma (Signet Classics (Paperback)),"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
2099,V: The New England Resistance,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0
1982,"The Visitant (The Anasazi Mysteries, Book 1)","God Emperor of Dune (Dune Chronicles, Book 4)",3.0,4,1.0
2100,VELVET SONG,"God Emperor of Dune (Dune Chronicles, Book 4)",1.0,2,1.0

In [41]:
author = rank.groupby(["user", "author"])["rating"].sum().reset_index()
author

          user                     author  rating
0            2         Mark P. O. Morford       0
1            8                 Adam Lebor       0
2            8                    Amy Tan       0
3            8                Ann Beattie       5
4            8               Carlo D'Este       0
...        ...                        ...     ...
810912  278854       Lilian Jackson Braun       0
810913  278854  Patricia Daniels Cornwell       7
810914  278854             Rita Mae Brown       6
810915  278854               SARAH GRAVES       0
810916  278854                  TAMI HOAG       8

[810917 rows x 3 columns]

In [44]:
stats = calc_corr_for_df("Stephen King", author[["user", "rating", "author"]], "author")
stats.sort_values("corr", ascending=False).head(40)

                         author target_author  almost_corr  user  corr
9153                Judith Hunt  Stephen King          4.0     5   1.0
13556  Patricia Campbell Hearst  Stephen King          2.0     3   1.0
6938     Isadore, Md. Rosenfeld  Stephen King          1.0     2   1.0
3411               Dalia Vargas  Stephen King          1.0     2   1.0
3414     Dame Catherine Cookson  Stephen King          1.0     2   1.0
3453                  Dan Sachs  Stephen King          1.0     2   1.0
11022          Lucille Colandro  Stephen King          1.0     2   1.0
5350                   Exbrayat  Stephen King          2.0     3   1.0
14647         Richard Bohringer  Stephen King          1.0     2   1.0
16539                Steve Zorn  Stephen King          1.0     2   1.0
8536            John Burningham  Stephen King          2.0     3   1.0
14656       Richard Chamberlain  Stephen King          1.0     2   1.0
6935        Isabelle Chin Chang  Stephen King          1.0     2   1.0
5319                Evan Morris  Stephen King          1.0     2   1.0
8494            John A. Sanford  Stephen King          1.0     2   1.0
8486             John  Davidson  Stephen King          1.0     2   1.0
6892             Irena Chalmers  Stephen King          1.0     2   1.0
1137        Arthur Edward Waite  Stephen King          1.0     2   1.0
8485      Johannes Mario Simmel  Stephen King          1.0     2   1.0
8472             Johan Huizinga  Stephen King          1.0     2   1.0
5286             Etienne Gilson  Stephen King          1.0     2   1.0
12612        Miguel Otero Silva  Stephen King          1.0     2   1.0
6960            Izaskun Arretxe  Stephen King          1.0     2   1.0
16342      Stefan Dziemianowicz  Stephen King          1.0     2   1.0
14788           Richard Slotkin  Stephen King          1.0     2   1.0
11257         MICHAEL AVI-YONAH  Stephen King          5.0     6   1.0
12555            Michele Stepto  Stephen King          1.0     2   1.0
3688               David Friend  Stephen King          1.0     2   1.0
11307           Madeline Bruser  Stephen King          1.0     2   1.0
6980         J. Davidson  Frame  Stephen King          1.0     2   1.0
8603               John E. MacK  Stephen King          1.0     2   1.0
16658              Susan Branch  Stephen King          1.0     2   1.0
8239                  Jim Grant  Stephen King          1.0     2   1.0
1310            Barbara Conklin  Stephen King          4.0     5   1.0
10617                  Liberica  Stephen King          1.0     2   1.0
5619               Fred Astaire  Stephen King          1.0     2   1.0
5618         FranÃƒ?Ã‚Â§oise Dorin  Stephen King          1.0     2   1.0
17124             Tessa Clayton  Stephen King          1.0     2   1.0
10680                Linda Goss  Stephen King          1.0     2   1.0
6772                Hugh Mackay  Stephen King          1.0     2   1.0

In [34]:
books[books["book-title"].str.contains("Vinci")]

,isbn,book-title,book-author
425,8401351421,El desarrollo de Leonardo da Vinci (BiografÃƒÂ­a...,Luis Racionero
748,0385504209,The Da Vinci Code,Dan Brown
1944,0452280907,Fortune Is a River : Leonardo Da Vinci and Nic...,Roger D. Masters
2586,0739307312,The Da Vinci Code,DAN BROWN
4064,8495618605,El Codigo Da Vinci / The Da Vinci Code,Dan Brown
8640,0765349671,The Da Vinci Legacy,Lewis Perdue
10434,1593150229,Secrets of the Code: The Unauthorized Guide to...,Dan Burstein
27158,0375432302,The Da Vinci Code (Random House Large Print),DAN BROWN
27733,0553378570,The Memory Cathedral: A Secret History of Leon...,Jack Dann
53819,0192815385,The Notebooks of Leonardo Da Vinci (World's Cl...,Leonardo Da Vinci
61130,0972952977,Da Vinci Code Decoded: The Truth Behind the Ne...,Martin Lunn
67805,3404920023,Die Kathedrale der Erinnerung. Das geheime Leb...,Jack Dann
69786,0451409965,The Da Vinci Deception (Inspector Jack Oxby No...,Thomas Swan
70104,078144165X,Cracking Da Vinci's Code: You've Read the Fict...,James Garlow
71604,0739302043,The Da Vinci Code,DAN BROWN
78396,1402718373,Cracking the Da Vinci Code : The Unauthorized ...,Simon Cox
95861,0385323816,How to Think Like Leonardo Da Vinci : Seven St...,Michael Gelb
114835,8478808337,Notas de Cocina de Leonardo Da Vinci,Leonardo Da Vinci
151799,0440508274,How to Think Like Leonardo da Vinci: Seven Ste...,MICHAEL J. GELB
160949,0684844524,Fortune is a River: Leonardo Da Vinci and Nicc...,Roger D. Masters
165320,0385504217,The Da Vinci Code,Dan Brown
171906,0553284959,Da Vinci Deception,Thomas Swan
199459,0300045093,Leonardo on Painting: An Anthology of Writings...,Martin Kemp
218654,0140169822,Leonardo Da Vinci,Kenneth Clark
218936,1410743748,The Da Vinci Papers,Kathy Williams
234149,1586170341,The Da Vinci Hoax: Exposing the Errors in The ...,Carl E. Olson
242922,0440508827,The How to Think Like Leonardo da Vinci Workbo...,MICHAEL J. GELB
243085,0785260463,Breaking The Da Vinci Code : Answers to the Qu...,"Darrell L., Ph.D Bock"
252066,B00008WFXL,The Da Vinci Code,Dan Brown
256240,3763759654,Technik und Geschichte der Hubschrauber. Sonde...,Rolf Besser
258376,0523417624,The Da Vinci Legacy,Lewis Purdue
258666,0739313126,The Da Vinci Code,DAN BROWN
261710,0486225720,The Notebooks of Leonardo Da Vinci (Volume 1),Leonardo Da Vinci
261711,0486225739,The Notebooks of Leonardo Da Vinci (Volume 2),Leonardo Da Vinci

In [57]:
from recommenders import AuthorCorrRecommender, BookCorrRecommender

In [58]:
brec = BookCorrRecommender()
brec.fit(rank[["user", "rating", "title"]])
brec("To Kill a Mockingbird", 10)

['Walden and Civil Disobedience (Penguin American Library)',
 'Don Quixote',
 'Blood of the Fold (Sword of Truth, Book 3)',
 'Civil Disobedience and Other Essays (Dover Thrift Editions)',
 'Shardik',
 'Sick of Shadows',
 "Hen's Teeth and Horse's Toes",
 'The Loved One',
 "Schindler's list",
 "Don't Make Me Stop this Car : Adventures in Fatherhood"]

In [62]:
arec = AuthorCorrRecommender()
arec.fit(author[["user", "rating", "author"]])
arec("J. K. Rowling", 10)

['RICHARD FORD',
 'Carol Endler Sterbenz',
 'Leon Garfield',
 'Apostolos Doxiadis',
 'Deborah and James Howe',
 'Deborah McCoy',
 'Sarah Dunn',
 'MARION CUNNINGHAM',
 'Kevin Johnson',
 'Pam Grout']

['Walden and Civil Disobedience (Penguin American Library)',
 'Don Quixote',
 'Blood of the Fold (Sword of Truth, Book 3)',
 'Civil Disobedience and Other Essays (Dover Thrift Editions)',
 'Shardik',
 'Sick of Shadows',
 "Hen's Teeth and Horse's Toes",
 'The Loved One',
 "Schindler's list",
 "Don't Make Me Stop this Car : Adventures in Fatherhood"]

In [28]:
%load_ext autoreload

In [29]:
%autoreload 2

In [30]:
pop.fit(rank)

ValueError: Length mismatch: Expected axis has 5 elements, new values have 3 elements